# Exported from Render on 2024-09-28T06:57:38Z
services:
- type: web
  name: spacely-csv-importer
  runtime: ruby
  repo: https://github.com/tonystrawberry/spacely-csv-importer
  plan: free
  envVars:
  - key: SUPABASE_DATABASE_USER
    sync: false
  - key: SUPABASE_DATABASE_PASSWORD
    sync: false
  - key: SUPABASE_DATABASE_NAME
    sync: false
  - key: SUPABASE_DATABASE_HOST
    sync: false
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  region: singapore
  buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake
    assets:clean;
  startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
version: "1"
